---
title: 파이썬 문법정리 6
date: 2023-05-24
description: 추가로 알게된 문법들에 대해 정리(예외처리)
tag: [파이썬, 문법]
---  

## 예외처리  
예외 처리 구문의 형식은 다음과 같다.  
```python 
try:
    실행할 명령
except 예외 as 변수:
    오류 처리문
else:
    예외가 발생하지 않을 때의 처리
```

## 예외의 종류
파이썬은 자주 발생하는 예외를 미리 정의해 두고 고유한 이름을 붙여 놓았다.  
예외의 원인별로 수많은 예외가 정의되어 있는데 다음 예외들이 빈번히 발생한다.  
- NameError : 명칭이 발견되지 않는다. 초기화하지 않은 변수를 사용할 때 발생한다.  
- ValueError : 타입은 맞지만 값의 형식이 잘못되었다.  
- ZeroDivisionError : 0으로 나누었다.  
- IndexError : 첨자가 범위를 벗어났다.  
- TypeError : 타입이 맞지 않다. 숫자가 필요한 곳에 문자열을 사용한 경우 등이다.  
try 블록에서 다른 종류의 예외가 여러 개 발생할 수도 있다.  
예외별로 except블록을 여러 개 작성해 두면 예외에 따라 적절한 except블록으로 점프한다.  
```python
str = "89"
try:
    score = int(str)
    print(score)
    a = str[5]
except ValueError:
    print("점수의 형식이 잘못되었습니다.")
except IndexError:
    print("첨자 범위를 벗어났습니다.")
print("작업완료")
#실행결과
89
첨자 범위를 벗어났습니다.
작업완료
```
  
## raise 
raise 명령은 고의적으로 예외를 발생시킨다.  
작업을 위한 선결 조건이 맞지 않거나 더 이상 진행할 숭 없는 치명적인 문제가 발생했을 때 호출원으로 예외를 던져 잘못되었음을 알린다.  
raise 뒤에 발생시킬 예외의 이름을 적는다.  
```python
def calcsum(n):
    if(n < 0):
        raise ValueError
    sum = 0
    for i in range(n+1):
        sum  = sum + i
    return sum

try:
    print("~10 =", calcsum(10))
    print("~-5 =", calcsum(-5))
except ValueError:
    print("입력값이 잘못되었습니다.")

#실행결과
~10 = 55
입력값이 잘못되었습니다.
```
1부터 지정한 정수까지 합계를 구하는 calcsum함수는 반드시 0보다 큰 인수를 받아야 한다.  
범위를 지정하는 인수 n이 음수라면 작업 지시가 잘못되었으므로 합계를 구할 수 없으며 이럴 때 예외를 던져 잘못을 알린다.  
값이 잘못되었다는 뜻으로 ValueError 예외를 던졌는데 상황에 꼭 맞는 예외를 직접 정의할 수도 있다.  
  
## finally  
finally 블록은 예외 발생 여부와 성관없이 반드시 실행해야 할 명령을 지정한다.  
메모리나 자원을 할당한 후 해제해야 하는데 이런 구문을 finally블록에 작성하면 예외 발생 여부에 상관없이 항상 이 구문을 실행한 후 전체 블록을 빠져 나온다.  
```python
try:
    print("네트워크 접속")
    a = 2 / 0
    print("네트워크 통신 수행")
finally:
    print("접속 해제")
print("작업 완료")
#실행결과
네트워크 접속
접속 해제
Traceback (most recent call last):
...
```
  
## assert  
assert 문장은 프로그램의 현재 상태가 맞는지 확인한다.  
점검할 조건과 조건이 거짓일 때 보여 줄 메시지를 지정한다.  
assert 조건, 메시지
조건을 점검해 보고 참이면 현재 상태가 정상적이라고 판단하여 아무 일도 하지 않는다.  
거짓이면 AssertionError예외를 발생시키고 프로그램을 즉시 중지시키며 메시지를 보여준다.  
메시지가 필요없으면 생략해도 상관없다.  
```python
score = 128
assert score <= 100, "점수는 100 이하여야 합니다"
print(score)
```
assert는 이상이 발생하는 즉시 이를 확인하여 알려 주는 역할을 한다.  
assert를 우리말로 번역하자면 "이 조건이 맞는지 지금 당장 확인하라"는 뜻이다.  
의심이 갈만한 상황에 대해 assert를 군데군데 작성해 두면 문제를 조기에 발견하는데 큰 도움이 된다.  

